### PR TITLE
feat: add support for max ports per vm

### PR DESCRIPTION
**Pull request by nikhilmakhijani**
Issue #123 : Adding support for max ports per vm

### CODE REVIEW

**Comment by nikhilmakhijani** [comment]
@apeabody/@g-awmalik could you please check

**Comment by imrannayer** [comment]
@nikhilmakhijani [enable_dynamic_port_allocation](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_router_nat#enable_dynamic_port_allocation) needs to be `true` to set `max_ports_per_vm`. Can you plz ignore this value in terraform code if `enable_dynamic_port_allocation` is set to `false`.

```
  max_ports_per_vm  = var.enable_dynamic_port_allocation ? var.max_ports_per_vm : null
```

Also add it to variable max_ports_per_vm description "this will be ignored if enable_dynamic_port_allocation is set to false"

**Comment by nikhilmakhijani** [comment]
> this will be ignored if enable_dynamic_port_allocation is set to false
Makes sense! I have added the changes suggested by you.

**Comment by nikhilmakhijani** [comment]
> @nikhilmakhijani [enable_dynamic_port_allocation](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_router_nat#enable_dynamic_port_allocation) needs to be `true` to set `max_ports_per_vm`. Can you plz ignore this value in terraform code if `enable_dynamic_port_allocation` is set to `false`.
> 
> ```
>   max_ports_per_vm  = var.enable_dynamic_port_allocation ? var.max_ports_per_vm : null
> ```
> 
> Also add it to variable max_ports_per_vm description "this will be ignored if enable_dynamic_port_allocation is set to false"

Makes sense! I have added the changes suggested by you.

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
