### PR TITLE
fix(enable_endpoint_independent_mapping=false)!: upgraded versions.tf to include minor bumps from tpg v5

### PR DESCRIPTION
**Pull request by g-awmalik**
Fixes: #112, #113

### CODE REVIEW

**Comment by imrannayer** [comment]
@g-awmalik there is a behavior change in 5.x. Default value of `enable_endpoint_independent_mapping` is now set to `FALSE`. It was `TRUE` pre 5.X. 
Should we make it a breaking change?

**Comment by imrannayer** [comment]
@g-awmalik for some reason gcloud command is returning an extra information `autoNetworkTier`. We may need to add it in  [test data](https://github.com/terraform-google-modules/terraform-google-cloud-nat/blob/master/test/integration/basic/testdata/TestBasic.json)

**Comment by apeabody** [comment]
> @g-awmalik there is a behavior change in 5.x. Default value of `enable_endpoint_independent_mapping` is now set to `FALSE`. It was `TRUE` pre 5.X. Should we make it a breaking change?

Alternatively we could switch the variable from `null` to `true` which maintain the previous behavior and so avoid a breaking change on requiring tpg v5.

**Comment by apeabody** [comment]
> @g-awmalik for some reason gcloud command is returning an extra information `autoNetworkTier`. We may need to add it in [test data](https://github.com/terraform-google-modules/terraform-google-cloud-nat/blob/master/test/integration/basic/testdata/TestBasic.json)

fixed and committed to repo

**Comment by apeabody** [comment]
> > @g-awmalik there is a behavior change in 5.x. Default value of `enable_endpoint_independent_mapping` is now set to `FALSE`. It was `TRUE` pre 5.X. Should we make it a breaking change?
> 
> Alternatively we could switch the variable from `null` to `true` which maintain the previous behavior and so avoid a breaking change on requiring tpg v5, however that would differ from the provider new default: https://registry.terraform.io/providers/hashicorp/google/5.0.0/docs/guides/version_5_upgrade#enable_endpoint_independent_mapping-now-defaults-to-apis-default-value-which-is-false

Looks like the preferable option is, in-line with tpg v5 default, is `false`.  So we'll make this a breaking change.

**Review by apeabody — APPROVED** [review]

**Pull request merged**
