### PR TITLE
fix!: Set endpoint-independent-mapping default to false

### PR DESCRIPTION
**Pull request by sclausson**
Fix for issue https://github.com/terraform-google-modules/terraform-google-cloud-nat/issues/112

### CODE REVIEW

**Comment by imrannayer** [comment]
@sclausson @apeabody this will be breaking change. Since we already have 4.0 lined up this can go in there.

**Comment by imrannayer** [comment]
@sclausson Integration test is failing for enableEndpointIndependentMapping value. Can you plz change this to false in:
1) https://github.com/terraform-google-modules/terraform-google-cloud-nat/blob/master/test/integration/advanced/testdata/TestAdvanced.json
2) https://github.com/terraform-google-modules/terraform-google-cloud-nat/blob/master/test/integration/basic/testdata/TestBasic.json
3) https://github.com/terraform-google-modules/terraform-google-cloud-nat/blob/master/test/integration/subnetworks/testdata/TestSubnetworks.json

**Comment by imrannayer** [comment]
@sclausson r u still working on this PR?

**Comment by apeabody** [comment]
Thanks @sclausson - Included with test fixture updates in #129

**Pull request closed without merging**
