### PR TITLE
Adding log_config block

### PR DESCRIPTION
**Pull request by rafaelromcar**
The block log_config was missing https://www.terraform.io/docs/providers/google/r/compute_router_nat.html#log_config

It is now added, disabled by default.

### CODE REVIEW

**Comment by rafaelromcar** [comment]
I'm sorry, I didn't have the time. I will try to do it before Monday. Busy week.

**Comment by niven01** [comment]
+1

**Comment by morgante** [comment]
@rafaelromcar Are you still planning to pick this up or should we reassign?

**Comment by rafael-romero-carmona-claranet** [comment]
Hello @morgante I did the requested modifications and pushed them. I hope it is OK now. Still, I think there is a problem with the README.md. It has been generated with make generate_docs but the diff looks quite big.

Let me know if something else is needed.

**Comment by rafaelromcar** [comment]
Hello @morgante I did the requested modifications and pushed them. I hope it is OK now. Still, I think there is a problem with the README.md. It has been generated with make generate_docs but the diff looks quite big.

Let me know if something else is needed.

**Comment by rafael-romero-carmona-claranet** [comment]
Hello @morgante I implemented what you asked. Is there anything more you want me to do? If not, could you merge this?

Thanks

**Comment by rafaelromcar** [comment]
Hello @morgante I implemented what you asked. Is there anything more you want me to do? If not, could you merge this?

Thanks

**Pull request merged**
